### PR TITLE
fix(optionset): reset changedOriginalFieldValues when model changes

### PR DESCRIPTION
**Pull request by Birkbjo**

### CODE REVIEW

**Comment by varl** [comment]
Patch looks good to me.

One nitpick:

`//reset field values when model changes`

I can see that the code resets the field values when the model changes, what I want to know from the comment is "why" we need to do this.

**Comment by Birkbjo** [comment]
The why comment has been added

**Comment by HendrikThePendric** [comment]
@Birkbjo could you have a look at the changed files and confirm this is looking good now? We'll have to resolve some small conflicts to merge this into Master. I can take care of this, i've self-assigned this PR.

**Comment by Birkbjo** [comment]
LGTM!

**Pull request merged**
